### ISSUE TITLE
Incorrectly identifying cluster state change

### ISSUE THREAD

**Issue by doddatpivotal** [vmware/terraform-provider-tanzu-mission-control#30]
### Describe the bug

I created a cluster where I did not specify the following within my node pool.

            cloud_label = {}
            node_label  = {}

The cluster created fine, however each time the cluster state is refreshed for successive "applies" terraform keeps saying that there is a difference been my state and the remote implementation because of this.

I don't think this should happen.

### Reproduction steps

```bash
1. Create cluster without the labels and apply
2. Run apply again, and you will see the diff
```

### Expected behavior

I did not change the definition, so I did not expect the state change.

**Comment by shreyassreenivas** [comment]
Hi @doddatpivotal , 
Thank you for raising this issue and helping the provider experience get better.

Let me explain the behavior here.
 
 1. A Cluster is created with config X via terraform apply
 2. The Cluster creation is successful with the same config x on the TMC server side 
 3. Now, some new sever side  labels/annotations are added to the cluster config X. One example of such a label would be adding the resource owner label to the resource. Adding additional labels/annotations is common practice (even seen in Kubernetes resource creations). Lets call this config Y 
 4. Next time when you invoke terraform apply again, the terraform tries to fetch the latest state of the cluster from TMC. ie Config Y will be fetched and the state is refreshed. We have update the terraform state to config Y because we have to show the present source of truth
 5. But in tf file the config X is present but now it has been updated to config Y. Hence terraform shows there is a state change. This state change is not altering or overriding the spec, only the labels and annotations are appended.

Possible solution :
If the labels are added on the server-side, we will try to suppress the state change diff shown in the terraform.

**Comment by doddatpivotal** [comment]
Or could we make the keys required on the schema?  If they were required to be included, and specified an empty object, I would have done that from the start.

**Comment by shreyassreenivas** [comment]
@doddatpivotal , 
marking the keys required would not solve the problem you are facing, ie the state change diff.
Even if the labels/keys are provided and applied on the TMC side, the subsequent refresh of the terraform state will show the diff. The diff will always be the labels that are getting added from the sever.

Terraform SDK has a solution for such a scenario, which is suppressing the wrong diffs shown to the users. We will add this suppressor to  "cloud_label & node_label " attributes. The limitation of this approach is that the suppressor has to be defined per attribute level.

**Comment by shobha2626** [comment]
Cloud and node labels are no more supported for the TKGm workload clusters. Hence, removing these fields from the version v1.0.2. The state file does not show the diff as they are now being removed.
