### ISSUE TITLE
Scaling cluster has no effect

### ISSUE THREAD

**Issue by doddatpivotal** [vmware/terraform-provider-tanzu-mission-control#33]
### Describe the bug

I am unable to use terraform to scale a cluster that was previously created using terraform.

### Reproduction steps

```bash
1. Create a TKGS cluster. Everything is working.
2. Change spec.tkg_service_vsphere.topology.node_pools.spec.worker_node_count and apply.  Terraform output recognizes the change, prompts for acceptance, and then reports success.
3. However, there is no impact.  And if I go to the TMC UI and view the Node Pools for that cluster it represents the previous value.
```

### Expected behavior

I would expect for the cluster to be scaled.

**Comment by shobha2626** [comment]
Hi @doddatpivotal, please make use of `nodepool` resource to do any changes related to node pool specific fields (like worker_node_count).
While creating a TKG cluster, you can provide the default node pool parameters as part of the spec. Later for any CRUD operation make use of the node pool resource. This is very similar to the TMC UI functionality.

Examples to make use of node pool resource can be found here - https://github.com/vmware/terraform-provider-tanzu-mission-control/blob/main/docs/resources/cluster_node_pool.md

As an action item, we will add a new guide document to mention the same.

**Comment by doddatpivotal** [comment]
Thanks @shobha2626 , but this does not make sense to me as a user.  Why would the spec.tkg_service_vsphere.topology.node_pools.spec.worker_node_count only be relavant for the initial deployment. Then I have to use a different resource.

**Comment by doddatpivotal** [comment]
Doesn't having different resources for day 1 deployment and day 2 updates imply different sources of truth for infra as code?

**Comment by shreyassreenivas** [comment]
Thank you for the issue and for discussing this default nodepool scenario.

The present state of the art in TMC is that,
While creating a cluster we need one nodepool to be defined because the cluster creation requires at least one nodepool to be present, but cluster and nodepool are two individual resources.
Nodepool scaling is supported via nodepool resource [this is applicable for the nodepool specified during cluster creation]

In terraform we initially tried to combine two API resources [cluster & nodepool] as one terraform resource but this is not advisable as it will report wrong diffs.

For example , if you scale the default nodepool from 5 ~> 6 and do a cluster get, the nodepool in the cluster spec will still reflect the old values.

The suggested solution would be,
For new nodepools, we can use nodepool resources to scale up or down by referencing the cluster in nodepool fullname.

For default nodepool, we will try to provide abstraction in the cluster spec itself as adoption in terraform is not intutive.

Will add additional docs to explain this sceanrio so it becomes easier to the users.

**Comment by akceleste** [comment]
I think you are missing the point relative to the node pool question.  you are trying to replicate what is in TMC - but that is not the goal of infrastructure as code.  If we wanted the behavior to imitate TMC we would use the TMC CLI or the TMC UI. We are using terraform to avoid using the CLI and the UI because we want the behavior to be different.

**Comment by doddatpivotal** [comment]
@akceleste can you be specific on which comments in the thread above are missing the point?

**Comment by shreyassreenivas** [comment]
V1alpaha1 APIs of TMC has been designed such that the cluster and node pools to be considered as two different resources.
but we have taken this feedback and will incorporate in the v1alpha2 apis.

Present behaviour of the provider cannot be change as this will impact diff changes and might result in unknown behaviour. 

So requesting everyone to use Cluster for creating and node pool resources for any other options on nodepool
